# Page settings

baseURL = "localhost:1313"
languageCode = "en"
title = ""
theme = "devresume"
googleAnalytics = ""


[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#000000"
    textPrimaryColor = "#000000"

    [params.profile]
        enable = true
        name = "Yan Zhang"
        tagline = "Embededd Software Developer"

    [params.contact]
        enable = true
        location = "New York"
        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "(925)494-3211"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "663yan@gmail.com"
    
    [params.social]
        enable = true
        [[params.social.list]]
        icon = "fas fa-globe"
        url = "https://#"
        text = "zhangy.me"
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https:///github.com/#"
        text = "h-bar"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/#"
        text = "663yan"


    [params.summary]
        enable = true
        text = ""