# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "devresume"
googleAnalytics = ""


[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#000000"
    textPrimaryColor = "#000000"

    [params.profile]
        enable = true
        name = "Yan Zhang"
        tagline = "Senior Software Engineer"

    [params.contact]
        enable = true
        location = "New York"
        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "(925)494-3211"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "663yan@gmail.com"
    
    [params.social]
        enable = true
        [[params.social.list]]
        icon = "fas fa-globe"
        url = "https://#"
        text = "zhangy.me"
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https:///github.com/#"
        text = "h-bar"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/#"
        text = "663yan"


    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."